default: &default
  adapter: :postgresql
  pool: 5
  timeout: 5000
  username: belajarrails
  password: password123
  host: localhost

development:
  <<: *default
  database: template1

test:
  <<: *default
  database: myapp_test

production:
  <<: *default
  database: myapp_production
