# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6422ac35ac2594f4a20737120f89162b189c98c0e2aff1b301a583d2529eb7166b23cc726a3e74494770eb9547bb906282d5d611be876a9a71ef273a85f6b492

test:
  secret_key_base: ba4c447f60ac4c75b0e40dcb1c265a001a29060c679fff1356ba81f63e96e83ea0ed02553aeaf56168419f96bac9ff965191df5f75472e0c633e654e1311a63c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
